![](ubc_header.png)

# Climate-Friendly Food Systems (CFFS) Labelling Project

### The University of British Columbia

****

## Part I: Data Preprocessing

## Set up and Import Libraries

In [1]:
#pip install -r requirements.txt

In [2]:
import pandas as pd
import glob
import os
import xml.etree.ElementTree as et

In [3]:
# # RUN ONLY ONCE
# # os.chdir is used to change the current directory to the specified path
os.chdir("../") # Sets path to the repo folder as it is one level above where this file exists!
path = os.getcwd()
print(path)

/Users/ankurbhardwaj/Desktop/SEEDS/CFFS_Label_2024_25

****

## Load Data Files

### Set Data File Path

In [4]:
# Select data file path for the chosen venue and time range where the recipes data stored
RESTAURANT_FOLDER_NAME = "SUMMER_CONF"

# List all the files in the respective restaurant folder
filepath_list = glob.glob(os.path.join(os.getcwd(), "data", "raw", RESTAURANT_FOLDER_NAME, "*.oc"))

filepath_list

['/Users/ankurbhardwaj/Desktop/SEEDS/CFFS_Label_2024_25/data/raw/SUMMER_CONF/summer_conf_25_mar_2025.oc.oc']

### Import Items List

In [5]:
# Read items.xml files in the filepath_list and construct a dataframe
ItemId = []
Description = []
CaseQty = []
CaseUOM = []
PakQty = []
PakUOM = []
InventoryGroup = []


# from the items xml file, findtext of CaseQty, CaseUOM, PakQty, PakUOM, and InventoryGroup
# then append it on the lists above

for filepath in filepath_list:
    path = filepath + '/Items.xml'
    if os.path.isfile(path):
        xtree = et.parse(path)
        xroot = xtree.getroot()
        for item in xtree.iterfind('Item'):
            ItemId.append(item.attrib['id'])
            Description.append(item.findtext('Description'))
            CaseQty.append(item.findtext('CaseQty'))
            CaseUOM.append(item.findtext('CaseUOM'))
            PakQty.append(item.findtext('PakQty'))
            PakUOM.append(item.findtext('PakUOM'))
            InventoryGroup.append(item.findtext('InventoryGroup'))

            
# Create a dataframe from the lists created above.
        
Items = pd.DataFrame({'ItemId': ItemId, 'Description': Description, 'CaseQty': CaseQty, 
                      'CaseUOM': CaseUOM, 'PakQty': PakQty, 'PakUOM': PakUOM, 'InventoryGroup': InventoryGroup}
                    )

Items.drop_duplicates(inplace=True)

Items.reset_index(drop=True, inplace=True)

In [6]:
# creates a new array with unique ItemIds
all_id_list = Items["ItemId"].unique()

In [7]:
# Gives you the list of breads
breadlist = []


# If the items in the Items list is a "LOAF", "SANDWICH", or "BREAD" then we should add it in the breadlist
# We append it onto the breadlist at position row["ItemId"]
for ind, row in Items.iterrows():
    if ("LOAF" or "SANDWICH" "BREAD") in row["Description"]:
        breadlist.append(row["ItemId"])

breadlist

['I-71503']

In [8]:
Items = Items[~Items["InventoryGroup"].isin(["DISPOSABLES", "SUPPLY"])]

In [9]:
# Based on info below there are 486 rows and 7 columns
Items.shape

(262, 7)

In [10]:
Items.dtypes

ItemId            object
Description       object
CaseQty           object
CaseUOM           object
PakQty            object
PakUOM            object
InventoryGroup    object
dtype: object

In [11]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "Items_List.csv")
Items.to_csv(path, index = False, header = True)

### Import Ingredients List

In [12]:
# Read ingredients.xml files in the filepath_list and construct a dataframe
IngredientId = []
Conversion = []
InvFactor = []
Qty = []
Recipe = []
Uom = []

# Using the Ingredients XML file, we extract attributes containing ingredients, conversion, invFactor, qty, recipe, and uom. 
# Then we append it onto the IngredientId, Coversion, InvFactor, Qty, Recipe, and Uom lists
# Then we create a dataframe using the lists created. 

for filepath in filepath_list:
    path = filepath + '/Ingredients.xml'
    if os.path.isfile(path):
        xtree = et.parse(path)
        xroot = xtree.getroot()
        for x in xtree.iterfind('Ingredient'):
            IngredientId.append(x.attrib['ingredient'])
            Conversion.append(x.attrib['conversion'])
            InvFactor.append(x.attrib['invFactor'])
            Qty.append(x.attrib['qty'])
            Recipe.append(x.attrib['recipe'])
            Uom.append(x.attrib['uom'])
    
Ingredients = pd.DataFrame({'IngredientId': IngredientId, 'Qty': Qty,'Uom': Uom, 'Conversion': Conversion, 
                      'InvFactor': InvFactor,'Recipe': Recipe}).drop_duplicates()
Ingredients.drop_duplicates(subset=["IngredientId", "Recipe"], inplace=True)

Ingredients.reset_index(drop=True, inplace=True)

In [13]:
# This will output the IngredientId on the right side and the number of times the ingredient appears in the Ingredients
# dataframe on the left side. 

# The duplicated() method returns a Series with True and False values that describe which rows in the DataFrame are 
# duplicated and not.

check = Ingredients["IngredientId"].duplicated()

# The line below tells us at which index is the ingredient duplicated. For example I-4598 exists on index 2 of the dataframe and
# then again on index 8. So duplicate is first true on index 8, which is why it is printed below. It also appears in a below 
# index so it is printed again with that index number. 
Ingredients["IngredientId"][check]

16      I-6026
26      I-5983
27      I-6026
29      I-6026
33      I-4598
        ...
906     P-9745
907     I-4967
908     P-9756
909    P-18746
910    P-18746
Name: IngredientId, Length: 523, dtype: object

In [14]:
Ingredients

    IngredientId      Qty Uom  Conversion InvFactor   Recipe
0        P-48933    1.000  Kg  1.00000000    1.0000  P-10113
1         I-4658    2.270  Kg  2.20462000    0.6942  P-10496
2        I-56382    1.000   L  1.00000000    0.3058  P-10496
3         I-4598    1.000  CT  1.00000000    0.0013  P-12954
4         I-2074    1.000  Kg  2.20462000    0.0400  P-14535
..           ...      ...  ..         ...       ...      ...
910      P-18746    1.200  Kg  1.00000000    1.2000   P-9767
911      I-13050   13.000  lb  1.00000000    1.5294   P-9851
912       I-4521   12.000  lb  1.00000000    1.4118   P-9851
913      P-71660  150.000   g  0.00100000    1.0000  R-71663
914      P-71662  150.000   g  0.00100000    1.0000  R-71663

[915 rows x 6 columns]

In [15]:
Items

,ItemId,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-7631,5 SPICE POWDER,1.000,ea,1.000,lb,SPICES
1,I-3617,ALLSPICE GROUND SHAKER,8.000,each,454.000,g,SPICES
2,I-11181,ANISE STAR WHOLE,8.000,each,240.000,g,SPICES
3,I-4971,ARTICHOKE 1/4*CUT,6.000,LG CAN,2.420,Kg,PRODUCE
4,I-65741,BACON 2.5MM NATURALLY SMKD,5.000,Kg,1.000,Kg,MEAT
...,...,...,...,...,...,...,...
257,I-2171,YOGURT STRAWB*POUCH,4.000,POUCH,2.000,Kg,DAIRY
258,I-52884,YOGURT VANILLA*STR 4KG TUB,1.000,4KG,4.000,Kg,DAIRY
259,I-72037,YOGURT YOGG*COCONUT VEGAN,3.500,Kg,1.000,Kg,DAIRY
260,I-4962,ZUCCHINI BC,25.000,lb,1.000,lb,PRODUCE
261,I-4967,ZUCCHINI MED FCY MX,25.000,lb,1.000,lb,PRODUCE

In [16]:
Ingredients.shape

(915, 6)

In [17]:
Ingredients.dtypes

IngredientId    object
Qty             object
Uom             object
Conversion      object
InvFactor       object
Recipe          object
dtype: object

In [18]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "Ingredients_List.csv")
Ingredients.to_csv(path, index = False, header = True)

### Import Preps List

In [19]:
# Read preps.xml files in the filepath_list and construct a dataframe
PrepId = []
Description = []
PakQty = []
PakUOM = []
InventoryGroup = []


# Here we do the same thing for the Preps XML file where we find the columns using attrib function and then append it onto
# the dataframe called Preps. 

for filepath in filepath_list:
    path = filepath + '/Preps.xml'
    if os.path.isfile(path):
        xtree = et.parse(path)
        xroot = xtree.getroot()
        for x in xtree.iterfind('Prep'):
            PrepId.append(x.attrib['id'])
            Description.append(x.findtext('Description'))
            PakQty.append(x.findtext('PakQty'))
            PakUOM.append(x.findtext('PakUOM'))
            InventoryGroup.append(x.findtext('InventoryGroup'))
    
Preps = pd.DataFrame({'PrepId': PrepId, 'Description': Description,
                  'PakQty': PakQty, 'PakUOM':PakUOM, 'InventoryGroup': InventoryGroup}).drop_duplicates()
preps_columns = Preps.columns
Preps.drop_duplicates(subset=["PrepId"], inplace=True)

Preps.reset_index(drop=True, inplace=True)

In [20]:
Preps

      PrepId                 Description   PakQty PakUOM       InventoryGroup
0    P-26205     BATCH|Sauteed Mushroom*    4.250     Kg                 PREP
1    P-43762   Butter chickpea CHICKPEA*  100.000     Kg                 PREP
2    P-24750          CHOPPED|Cilantro *  500.000      g
3    P-62139       CHOPPED|Cilantro|NEW*   42.000      g
4    P-26188     COOKED||Elbow Macaroni*    1.250     Kg  ZDONT USE OK - PREP
..       ...                         ...      ...    ...                  ...
223  P-16392       YIELD|Yellow Onions.*    8.900     Kg
224  P-57145        YIELD|Yellow Pepper*    8.300     Kg
225   P-9756             YIELD|Zucchini*    0.900     Kg
226  P-20249            YIELD|Zucchini*.   10.800     Kg
227  P-71592  YIELDILOAF WHITE 5/8 CLUB*   22.000  slice

[228 rows x 5 columns]

In [21]:
# This tells us that there are not any duplicates in the Preps dataframe. There is a different process|ingredient pair for 
# all the recipes. 
check = Preps["PrepId"].duplicated().any()
print(check)

False

In [22]:
# There are 546 rows and 5 columns
Preps.shape

(228, 5)

In [23]:
Preps.dtypes

PrepId            object
Description       object
PakQty            object
PakUOM            object
InventoryGroup    object
dtype: object

In [24]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "Preps_List.csv")
Preps.to_csv(path, index = False, header = True)

### Import Products List

In [25]:
# Read products.xml files in the filepath_list and construct a dataframe
ProdId = []
Description = []
SalesGroup = []

# From the XML file for products append the id into ProdId, description into Description, and SalesGroup into SalesGroup list.
# Make a dataframe out of the 3 lists
# Then also drop the duplicates in the Products dataframe

for filepath in filepath_list:
    path = filepath + '/Products.xml'
    if os.path.isfile(path):
        xtree = et.parse(path)
        xroot = xtree.getroot()
        for x in xtree.iterfind('Prod'):
            ProdId.append(x.attrib['id'])
            Description.append(x.findtext('Description'))
            SalesGroup.append(x.findtext('SalesGroup'))
        
Products = pd.DataFrame({'ProdId': ProdId, 'Description': Description, 'SalesGroup': SalesGroup})
Products.drop_duplicates(inplace=True)

Products.reset_index(drop=True, inplace=True)

In [26]:
Products

    ProdId          Description SalesGroup
0  R-71663  23|Hash Brown|RATIO       FOOD

In [27]:
Products.dtypes

ProdId         object
Description    object
SalesGroup     object
dtype: object

In [28]:
Products.shape

(1, 3)

In [29]:
Products.dtypes

ProdId         object
Description    object
SalesGroup     object
dtype: object

In [30]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "Products_List.csv")
Products.to_csv(path, index = False, header = True)

### Import Conversions List

In [31]:
# Read conventions.xml files in the filepath_list and construct a dataframe
ConversionId = []
Multiplier = []
ConvertFromQty = []
ConvertFromUom = []
ConvertToQty = []
ConvertToUom = []

# From the XML file for Conversions append the id into ConversionId, multiplier into Multiplier, ConvertFrom->qty into 
# ConvertFromQty,ConvertFrom->uom into ConvertFromUom, ConvertTo->qty into ConvertToQty and and ConvertTo->uom into the
# CovertToUom list. 
# Make a dataframe out of the 3 lists
# Then also drop the duplicates in the Products dataframe


for filepath in filepath_list:
    path = filepath + '/Conversions.xml'
    if os.path.isfile(path):
        xtree = et.parse(path)
        xroot = xtree.getroot()
        for x in xtree.iterfind('Conversion'):
            ConversionId.append(x.attrib['id'])
            Multiplier.append(x.attrib['multiplier'])
            ConvertFromQty.append(x.find('ConvertFrom').attrib['qty'])
            ConvertFromUom.append(x.find('ConvertFrom').attrib['uom'])
            ConvertToQty.append(x.find('ConvertTo').attrib['qty'])
            ConvertToUom.append(x.find('ConvertTo').attrib['uom'])
    
    
Conversions = pd.DataFrame({'ConversionId': ConversionId, 'Multiplier': Multiplier, 'ConvertFromQty': ConvertFromQty,
                           'ConvertFromUom': ConvertFromUom, 'ConvertToQty': ConvertToQty, 'ConvertToUom': ConvertToUom}
                          ).drop_duplicates()

Conversions.reset_index(drop=True, inplace=True)

In [32]:
# Here we can see for example that to convert 1.14 L to 1 L the multiplier is 0.877 since 1/1.14 = 0.877
Conversions

,ConversionId,Multiplier,ConvertFromQty,ConvertFromUom,ConvertToQty,ConvertToUom
0,,1.00000000,1.0000,XXX,1.0000,L
1,,0.87719298,1.0000,1.14L,1.1400,L
2,,0.66666667,1.0000,1.5L,1.5000,L
3,,0.57142857,1.0000,1.75 L,1.7500,L
4,,0.50000000,1.0000,2L,2.0000,L
...,...,...,...,...,...,...
184,I-43958,0.02000000,1.0000,each,50.0000,g
185,I-45114,0.03333333,0.5000,fl oz,15.0000,g
186,I-56382,0.00100000,1.0000,L,1000.0000,g
187,I-60809,0.00406504,1.0000,cup,246.0000,g
188,I-60809,0.00101626,1.0000,qt,984.0000,g

In [33]:
all_id_list = Items["ItemId"].unique()
all_conv_list = Conversions["ConversionId"].unique()

print("All unique IDs list\n")
print(all_id_list)
print("\n")
print("All unique Conversions list\n")
print(all_conv_list)

All unique IDs list

['I-7631' 'I-3617' 'I-11181' 'I-4971' 'I-65741' 'I-3130' 'I-3141'
 'I-38906' 'I-3619' 'I-2567' 'I-3143' 'I-4515' 'I-3144' 'I-3149' 'I-75655'
 'I-3846' 'I-7064' 'I-3836' 'I-3837' 'I-73834' 'I-75652' 'I-4521'
 'I-13050' 'I-72009' 'I-4538' 'I-8060' 'I-2074' 'I-3159' 'I-3620' 'I-4589'
 'I-4572' 'I-4590' 'I-4593' 'I-3621' 'I-4598' 'I-4599' 'I-2110' 'I-14177'
 'I-73026' 'I-14179' 'I-11240' 'I-2141' 'I-3999' 'I-43958' 'I-4010'
 'I-4016' 'I-73368' 'I-5975' 'I-3622' 'I-3623' 'I-3624' 'I-2979' 'I-3625'
 'I-3627' 'I-3628' 'I-3223' 'I-5061' 'I-3629' 'I-50750' 'I-3229' 'I-11094'
 'I-6875' 'I-2217' 'I-65801' 'I-65802' 'I-2205' 'I-6832' 'I-3630'
 'I-11211' 'I-3631' 'I-2159' 'I-2157' 'I-2156' 'I-4640' 'I-3284' 'I-19631'
 'I-19540' 'I-3290' 'I-10865' 'I-2611' 'I-11207' 'I-4657' 'I-3632'
 'I-4658' 'I-9685' 'I-4660' 'I-3302' 'I-2309' 'I-17666' 'I-4508' 'I-4341'
 'I-4695' 'I-4708' 'I-4724' 'I-4767' 'I-4772' 'I-4983' 'I-4848' 'I-4919'
 'I-3321' 'I-1813' 'I-6443' 'I-1816' 'I-73476' 'I-3336' 'I-3337' 'I-11312'
 'I-4703' 'I-4709' 'I-3340' 'I-3341' 'I-71503' 'I-2220' 'I-60809'
 'I-31992' 'I-72404' 'I-4725' 'I-4729' 'I-4731' 'I-4732' 'I-4737' 'I-3367'
 'I-2898' 'I-3638' 'I-3182' 'I-56382' 'I-3387' 'I-3388' 'I-3390' 'I-71926'
 'I-3392' 'I-6014' 'I-6829' 'I-4745' 'I-3639' 'I-4375' 'I-10149' 'I-4679'
 'I-6779' 'I-17150' 'I-5010' 'I-6807' 'I-4381' 'I-3314' 'I-2911' 'I-3243'
 'I-3640' 'I-3641' 'I-5978' 'I-3404' 'I-3409' 'I-37842' 'I-71841'
 'I-30144' 'I-2648' 'I-69779' 'I-72822' 'I-3425' 'I-7766' 'I-48542'
 'I-41267' 'I-3429' 'I-2653' 'I-3431' 'I-3433' 'I-11813' 'I-3435'
 'I-41924' 'I-11557' 'I-3444' 'I-3643' 'I-6812' 'I-3642' 'I-3644' 'I-3447'
 'I-7787' 'I-3647' 'I-42230' 'I-3649' 'I-4785' 'I-4786' 'I-4787' 'I-4792'
 'I-4795' 'I-4796' 'I-4797' 'I-2658' 'I-3454' 'I-3458' 'I-3854' 'I-3855'
 'I-3856' 'I-3857' 'I-4819' 'I-15329' 'I-3476' 'I-66297' 'I-3099' 'I-3635'
 'I-74153' 'I-71953' 'I-6026' 'I-72913' 'I-17054' 'I-9379' 'I-45114'
 'I-10864' 'I-3524' 'I-7705' 'I-2697' 'I-2698' 'I-47774' 'I-63875'
 'I-3571' 'I-3572' 'I-27407' 'I-17667' 'I-17677' 'I-3910' 'I-3577'
 'I-3590' 'I-4894' 'I-2319' 'I-2254' 'I-9381' 'I-4896' 'I-4509' 'I-6820'
 'I-6028' 'I-3658' 'I-3657' 'I-3660' 'I-6027' 'I-15240' 'I-4913' 'I-3653'
 'I-3110' 'I-68035' 'I-3676' 'I-72461' 'I-3678' 'I-3677' 'I-3679'
 'I-72405' 'I-7791' 'I-3968' 'I-3654' 'I-4943' 'I-40436' 'I-9382' 'I-3695'
 'I-3696' 'I-5983' 'I-7061' 'I-7060' 'I-11669' 'I-6850' 'I-2171' 'I-52884'
 'I-72037' 'I-4962' 'I-4967']


All unique Conversions list

['' 'I-1813' 'I-2074' 'I-2159' 'I-2205' 'I-2217' 'I-2220' 'I-2254'
 'I-3141' 'I-3143' 'I-3144' 'I-3149' 'I-3159' 'I-3223' 'I-3229' 'I-3284'
 'I-3321' 'I-3367' 'I-3387' 'I-3388' 'I-3390' 'I-3392' 'I-3435' 'I-3458'
 'I-3571' 'I-3572' 'I-3577' 'I-3590' 'I-3617' 'I-3619' 'I-3620' 'I-3621'
 'I-3622' 'I-3623' 'I-3624' 'I-3625' 'I-3628' 'I-3629' 'I-3630' 'I-3631'
 'I-3632' 'I-3635' 'I-3638' 'I-3639' 'I-3640' 'I-3641' 'I-3642' 'I-3643'
 'I-3644' 'I-3647' 'I-3649' 'I-3653' 'I-3654' 'I-3657' 'I-3658' 'I-3660'
 'I-3676' 'I-3678' 'I-3679' 'I-3695' 'I-3854' 'I-4341' 'I-4375' 'I-4593'
 'I-4598' 'I-4599' 'I-4640' 'I-4679' 'I-4709' 'I-4745' 'I-4772' 'I-4894'
 'I-5983' 'I-6443' 'I-6812' 'I-6832' 'I-7060' 'I-7061' 'I-8060' 'I-9381'
 'I-10149' 'I-27407' 'I-31992' 'I-43958' 'I-45114' 'I-56382' 'I-60809']

In [34]:
# Here we have the number of items in the list that are a part of the "all_id_list" but not part of the "all_conv_list"
missing_conv_id = []

for item in all_id_list:
    if item not in all_conv_list:
        missing_conv_id.append(item)
        
missing_conv_id
print(len(missing_conv_id))

176

In [35]:
Conversions.shape

(189, 6)

In [36]:
Conversions.dtypes

ConversionId      object
Multiplier        object
ConvertFromQty    object
ConvertFromUom    object
ConvertToQty      object
ConvertToUom      object
dtype: object

In [37]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "Conversions_List.csv")
Conversions.to_csv(path, index = False, header = True)

***
## Data Summary

In [38]:
# Summary of raw data imported for evaluation
# Here we have a summary of the number of items, preps, ingredients, products, conversions

datasum = pd.DataFrame([Items.shape, Preps.shape, Ingredients.shape, Products.shape, Conversions.shape],
                       columns = ['count', 'columns'], 
                       index = ['Items', 'Preps', 'Ingredients', 'Products', 'Conversions'])
datasum

             count  columns
Items          262        7
Preps          228        5
Ingredients    915        6
Products         1        3
Conversions    189        6